### ISSUE TITLE
unexpected semantics of warmup configuration

### ISSUE THREAD

**Issue by o-** [smarr/ReBench#111]
I use rebench to record some data with `rebench someConfig -df someData`.
Then later I look at the data again using the exact same command.

I get twice different results printed to the console.

The reason is that the warmup config entry is used in a very surprising way.

Warmup runs are:

1. filtered when sending data to a webserver with fresh data
2. filtered when outputing statistics to the console with fresh data
3. not filtered when outputting to a data file
4. not filtered when outputing statistics to the console with existing data
5. idk what happens when sending data to a webserver with existing data

that seems like a potential footgun situation, at least I measured a whole lot of nonsense, by unfortunately assuming that (2) and (4) would give me the same number (ie. I assumed that `rebench someConfig -df someData` is idempotent).

**Comment by smarr** [comment]
Dear o-:

Just for reference, the semantics of warmup are documented here: https://rebench.readthedocs.io/en/latest/config/

```
**warmup:**

Consider the first N iterations as warmup and ignore them in ReBench's summary
statistics. Note, that warmup iterations are still persisted in the data file.
```

There may be an undesirable interaction with already existing data.
At the moment, I don't even know what the implemented semantics for summary statistics are.

I personally do not rely on the data reported on the console.
ReBench is not meant to be a data analysis or performance analysis tool by itself, so, I may just not have noticed.

If you are adventurous, perhaps you could have a look at the code?

**Comment by o-** [comment]
> There may be an undesirable interaction with already existing data.
>  At the moment, I don't even know what the implemented semantics for summary statistics are.

yes, in the case of data from existing files, the summary function ignores the warmup configuration when reporting.

> I personally do not rely on the data reported on the console.

sure, I just wanted to make it known, that this might be a bit strange for people using rebench

> If you are adventurous, perhaps you could have a look at the code?

sorry, I wrote a [ruby script](https://github.com/o-/rir-rebench-scripts/blob/master/diff.rb) that shows me the diff (and other stuff I care about) between two rebench data files.

**Comment by smarr** [comment]
> > I personally do not rely on the data reported on the console.
> 
> sure, I just wanted to make it known, that this might be a bit strange for people using rebench

Yes, thank you.

> > If you are adventurous, perhaps you could have a look at the code?
> 
> sorry, I wrote a [ruby script](https://github.com/o-/rir-rebench-scripts/blob/master/diff.rb) that shows me the diff (and other stuff I care about) between two rebench data files.

Well, that's the recommended approach anyway :)
Just for reference, here is what I am using for instance, a knitR file to generate plots from the data file: https://github.com/smarr/are-we-fast-yet/blob/master/report/overview.Rmd

**Comment by smarr** [comment]
@o- #116 hopefully fixes your issues.

Could you give it a spin?

**Comment by o-** [comment]
Thanks a lot, that does fix the issue.

**Comment by smarr** [comment]
Thanks for reporting and checking!
