### ISSUE TITLE
Fields returned by get_cpu_info have changed names

### ISSUE THREAD

**Issue by tobega** [smarr/ReBench#137]
get_cpu_info has changed its result so that e.g. 'brand' is now called 'brand_raw'. This causes rebench to not work.

**Comment by tobega** [comment]
'hz_advertised_raw' is changed to 'hz_advertised'.

**Comment by smarr** [comment]
Thanks a lot for reporting the issues!
I guess, either pining the version correctly, or indeed fixing this would be options.

Or both.

Is this urgent? I am not sure I'll get to this very soon.

**Comment by tobega** [comment]
No problem, I patched it for myself locally.

**Comment by smarr** [comment]
If you got a patch, PRs are very welcome :)

**Comment by tobega** [comment]
Simple enough, if you're ok with requiring latest version of cpuinfo

**Comment by smarr** [comment]
Yes, sure. I don't anticipate major issues for that. Thanks
