### ISSUE TITLE
Show standard out for failed build commands

### ISSUE THREAD

**Issue by richard-roberts** [smarr/ReBench#67]
Rebench does not show the standard output when a build script for a VM fails; currently only the return code is reported. It would be helpful to add the standard output of the build script to the report.

N.B: the build script is defined in the configuration file as an optional `build:` parameter for a VM configuration (not shown, but can be added [here](https://github.com/smarr/ReBench/blob/master/rebench.conf#L50).

**Comment by smarr** [comment]
This is solved with https://github.com/smarr/ReBench/pull/85/commits/9bd26a8f1ef08808cfa600c55734840b816f9037, which is part of #85.
