### ISSUE TITLE
Add option to export data as JSON 

### ISSUE THREAD

**Issue by richard-roberts** [smarr/ReBench#75]
Can we add a feature to export the data the as JSON. I believe JSON to be more versatile since most languages provide a library to process it. 

Here's a script that parses `benchmark.data` into a possible JSON format (a few things are missing, but the bulk of the work is done). The script first parses all the data and then organizes into a tree structure: 

- the top level contains experiments,
- each experiment is a collection of benchmarks, 
- each benchmark is a collection of per-VM results.

Feel free to suggest other organizations.

```python
import json

class Result:
    def __init__(self, line):
        parts = line.split("\n")[0].split("\t")        
        self.execution_time = float(parts[1])
        self.unit = parts[2]
        self.benchmark = parts[4]
        self.vm = parts[5]
        self.experiment = parts[6].split("-")[0]
        self.number_of_runs = int(parts[9])

    def as_json(self):
        return {
            "execution_time"      : self.execution_time,
            "unit"                : self.unit,
            "benchmark"           : self.benchmark,
            "vm"                  : self.vm,
            "experiment"          : self.experiment,
            "number_of_runs"      : self.number_of_runs,
        }

class Datum:
    def __init__(self, comment):
        self.info = {}
        self.results = []

        parts = comment.split(" ")
        for part in parts:
            if part.startswith("--") and "=" in part:
                key_with_prefix, value = part.split("=")
                key = key_with_prefix[2:]
                self.info[key] = value

    def commit(self): return self.info["commit-id"]
    def machine(self): return self.info["environment"]
    def add_result(self, line): self.results.append(Result(line))

    @staticmethod
    def extract():
        data = []

        current_datum = None
        with open("benchmark.data", "r") as f:
            lines = f.readlines()
            for line in lines:
                if line.startswith("#"):
                    if current_datum is not None:
                        data.append(current_datum)
                    current_datum = Datum(line)
                else:
                    current_datum.add_result(line)
        data.append(current_datum)
        return data


class Benchmark:
    def __init__(self, name):
        self.name = name
        self.vms = {}

    def add_result(self, result):
        if result.vm in self.vms.keys():
            self.vms[result.vm].append(result)
        else:
            self.vms[result.vm] = [result]

    def values(self, vm):
        return [r.execution_time for r in self.vms[vm]]

    def as_json(self):
        ret = {}
        for vm in self.vms.keys():
            ret[vm] = []
            for r in self.vms[vm]:
                ret[vm].append(r.as_json())
        return ret

class Experiment:
    def __init__(self, name):
        self.name = name
        self.benchmarks = {}

    def add_result(self, result):
        if result.benchmark in self.benchmarks.keys():
            self.benchmarks[result.benchmark].add_result(result)
        else:
            r = Benchmark(result.benchmark)
            r.add_result(result)
            self.benchmarks[result.benchmark] = r

    def as_json(self):
        ret = {}
        for key in self.benchmarks.keys():
            ret[key] = self.benchmarks[key].as_json()
        return ret

    @staticmethod
    def extract(data):
        experiments = {}

        for datum in data:
            results = datum.results
            for result in results:
            
                if result.experiment in experiments.keys():
                    experiments[result.experiment].add_result(result)

                else:
                    e = Experiment(result.experiment)
                    e.add_result(result)
                    experiments[result.experiment] = e

        return experiments


def save_as_json():
    ret = {}
    experiments = Experiment.extract(Datum.extract())
    for key in experiments.keys():
        ret[key] = experiments[key].as_json()

    with open("benchmark.data.json", "w") as f:
        f.write(json.dumps(ret))

if __name__ == "__main__":
    save_as_json()
```

**Comment by smarr** [comment]
Hm, I am not against a JSON export, but I'd expect it to be worse in every way. More verbose, and less versatile.
I'd also like to understand why you think that JSON is more versatile than [CSV](https://en.wikipedia.org/wiki/Comma-separated_values)?

Note that the delimiter is `\t`, because it makes it easier to load the file in Excel (if I remember correctly).

**Comment by richard-roberts** [comment]
Well, I don't it's necessarily more versatile than CSV; but most languages seem to have a library for processing JSON which is why I suggested it. Beyond that, being able to structure the results into a tree seems useful to me (the code above groups individual VM by benchmark names and then by experiment name). My use case, for the grouping, is [this interface](http://richardroberts.co.nz/moth) for exploring the results. Not need to integrate it if you don't think it's useful :)

**Comment by smarr** [comment]
For CSV, you don't even need a library. So, don't think this is a good argument.
Grouping by benchmark name is perhaps a UI decision.
Doesn't seem to be a general enough choice for ReBench with its support for various experiments, extra variables/arguments, etc.

Is it a big issue if you leave this as a post processing step?
I am rather inclined to remove features then to add them at the moment.

One thing worth thinking about is whether we want support for some generic post processing script.
But that might be better done externally too. Not sure something needs to be done specific to the information inside the experiments.

Also, your interface looks like you're rebuilding something like [Codespeed](https://github.com/tobami/codespeed/). There are variations of those systems around, none of them super general sadly.

**Comment by richard-roberts** [comment]
> Is it a big issue if you leave this as a post processing step?

No, not at all. I can't think of a good reason why the grouping I suggested would be useful outside of a UI, so it's probably best to favour minimalism and leave the output as it is. 

> One thing worth thinking about is whether we want support for some generic post processing script. But that might be better done externally too.

I haven't come up anything that can't be done easily as a post-process (my processing goes as far as grouping the data and changing the unit used for time. 

Thanks for the consideration either way!
